/**
 * Global type declarations for Next.js App Router.
 * RouteContext and PageProps are normally generated by `next build` into .next/types/.
 * This file provides them statically so TypeScript works before/without a build.
 */

/**
 * Context type for Next.js API route handlers with dynamic segments.
 * Example: RouteContext<'/api/books/[id]'> → ctx.params resolves to { id: string }
 */
declare type RouteContext<_T extends string = string> = {
  params: Promise<Record<string, string>>
}

/**
 * Props type for Next.js pages with dynamic segments.
 * Example: PageProps → props.params resolves to { id: string, ... }
 */
declare type PageProps<_T extends string = string> = {
  params: Promise<Record<string, string>>
  searchParams?: Promise<Record<string, string | string[] | undefined>>
}
